[versions]
agp = "8.7.1"
kotlin = "1.9.23"
coreKtx = "1.12.0"

ui = "1.6.4"
foundation = "1.6.4"
material3 = "1.2.1"
materialComponents = "1.11.0"
activity-ktx = "1.8.2"
activity-compose = "1.8.2"
lifecycle = "2.7.0"
junit = "4.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-components = { module = "com.google.android.material:material", version.ref = "materialComponents" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
