#pragma once
#define NRF_LOG_ENABLED 0
#define NRF_SECTION_ITER_ENABLED 1

#define NRF_SDH_ENABLED 1
#define NRF_SDH_DISPATCH_MODEL 2
#define NRF_SDH_CLOCK_LF_SRC 1
#define NRF_SDH_CLOCK_LF_RC_CTIV 0
#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 0
#define NRF_SDH_CLOCK_LF_ACCURACY 7
#define NRF_SDH_REQ_OBSERVER_PRIO_LEVELS 2
#define NRF_SDH_STATE_OBSERVER_PRIO_LEVELS 2
#define NRF_SDH_STACK_OBSERVER_PRIO_LEVELS 2
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_STACK_OBSERVER_PRIO 0
#define NRF_SDH_BLE_OBSERVER_PRIO_LEVELS 4
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_CENTRAL_LINK_COUNT 0
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 1
#define NRF_SDH_BLE_GAP_DATA_LENGTH 27
#define NRF_SDH_BLE_GAP_EVENT_LENGTH 6
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 247
#define NRF_SDH_BLE_GATTS_ATTR_TAB_SIZE 4096
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_BLE_SERVICE_CHANGED 1
#define NRF_SDH_SOC_ENABLED 1
#define NRF_SDH_SOC_STACK_OBSERVER_PRIO 0
#define NRF_SDH_SOC_OBSERVER_PRIO_LEVELS 2

// RTT 6.18a's buffer-configuration code assumes a nonzero secondary slot.
#define SEGGER_RTT_CONFIG_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_CONFIG_MAX_NUM_DOWN_BUFFERS 2
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_UP 8192
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_DOWN 2048
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 0
